---
- name: Configure Raddit App Instance
  hosts: all
  gather_facts: false
  become: true

  pre_tasks:
    - name: Install python for Ansible to work
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false

    - name: Ruby | Check if ruby install is present
      shell: test -x /usr/local/bin/ruby-install
      when: ansible_system == "Linux"
      ignore_errors: yes
      register: rubyinstall_present
      tags: ruby

    - name: Ruby | Ruby install | package dependencies
      apt: pkg={{ item }} state=present force="yes"  update_cache="yes"
      when: ansible_system == "Linux"
      with_items:
        - build-essential
        - libffi-dev
        - libgdbm-dev
        - libncurses5-dev
        - libreadline-dev
        - libreadline6-dev
        - libtinfo-dev
        - libyaml-dev
      become: yes
      tags: ruby

  tasks:
  - name: Ruby | Download rubyinstall
    get_url: url=http://github.com/postmodern/ruby-install/archive/v{{ ruby_install_version }}.tar.gz
           dest=/tmp/ruby-install-{{ ruby_install_version }}.tar.gz
    when: rubyinstall_present | failed
    tags: ruby

  - name: Ruby | Unpack ruby-install
    command: tar xf /tmp/ruby-install-{{ ruby_install_version }}.tar.gz
             chdir=/tmp
    when: rubyinstall_present | failed
    tags: ruby

  - name: Ruby | Run ruby-install install target
    command: make install
           chdir=/tmp/ruby-install-{{ ruby_install_version }}
    when: rubyinstall_present | failed
    become: yes
    tags: ruby

  - name: Ruby | Download list of rubies available
    command: ruby-install
    when: rubyinstall_present | failed
    become: yes
    tags: ruby 

  - name: Install Bundler
    gem:
      name: bundler
      state: present
      user_install: no

  - name: Add APT key
    apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com

  - name: Add MongoDB repo
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present

  - name: Install MongoDB package
    apt:
      name: mongodb-org
      state: present
      update_cache: yes

  - name: Start MongoDB
    systemd:
      name: mongod
      state: started
      enabled: yes

  - name: Download Unit File for Raddit
    get_url:
      url: https://gist.githubusercontent.com/Artemmkin/ce82397cfc69d912df9cd648a8d69bec/raw/7193a36c9661c6b90e7e482d256865f085a853f2/raddit.service
      dest: /etc/systemd/system/raddit.service
